# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

zinb_w_cov <- function(Y_mat, X_mat, z_vec, s_vec, tau_mukj = 1, S = 20000L, burn_rate = 0.5, tau_mu0 = 1, tau_phi = 1, tau_beta = 1, a_omega = 1, b_omega = 1, a_pi = 1, b_pi = 1, a_p = 1, b_p = 1, a_mu = 2, b_mu = 10, a_phi = 1, b_phi = 0.01, a_beta = 2, b_beta = 10, mu0_mean = 5, beta_lim = 5) {
    .Call(`_IntegrativeBayes_zinb_w_cov`, Y_mat, X_mat, z_vec, s_vec, tau_mukj, S, burn_rate, tau_mu0, tau_phi, tau_beta, a_omega, b_omega, a_pi, b_pi, a_p, b_p, a_mu, b_mu, a_phi, b_phi, a_beta, b_beta, mu0_mean, beta_lim)
}

rnorm_trunc <- function(mu, sigma, lower, upper) {
    .Call(`_IntegrativeBayes_rnorm_trunc`, mu, sigma, lower, upper)
}

exp_rs <- function(a, b) {
    .Call(`_IntegrativeBayes_exp_rs`, a, b)
}

unif_rs <- function(a, b) {
    .Call(`_IntegrativeBayes_unif_rs`, a, b)
}

half_norm_rs <- function(a, b) {
    .Call(`_IntegrativeBayes_half_norm_rs`, a, b)
}

norm_rs <- function(a, b) {
    .Call(`_IntegrativeBayes_norm_rs`, a, b)
}

